sudo: required
language: node_js
node_js:
- 8.9.4
cache:
  directories:
  - node_modules
services:
- docker
addons:
  sauce_connect:
    username: konstantinov90
    access_key: $SAUCELABS_API_KEY
jobs:
  include:
  # - stage: integration testing
    # before_script:
    # - npm run selenium-standalone install
    # - npm run preHermione
    # script:
    # - npm run selenium-standalone start &
    # - npm run hermioneTestServer &
    # - sleep 5
    # - npm run hermione
    # after_script: npm run postHermione
  - stage: unit testing
    script:
    - npm run lint
    - npm test
  - <<: *deploy_template
    stage: integration testing
    env:
    - APP=shri-2018-nodejs-homework-test
    deploy:
      <<: *deploy_script
      on:
        all_branches: true
    after_deploy:
    - npm run hermione
  - &deploy_template
    stage: deploy staging
    if: tag IS blank
    env:
    - APP=shri-2018-nodejs-homework-stag
    script: skip
    before_deploy:
    - docker build --no-cache --tag registry.heroku.com/$APP/web .
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    deploy: &deploy_script
      provider: script
      script:
      - docker push registry.heroku.com/$APP/web
      on:
        branch: master
  - <<: *deploy_template
    stage: deploy production
    if: tag IS present
    env:
    - APP=shri-2018-nodejs-homework-prod
    deploy:
      <<: *deploy_script
      on:
        tags: true
