sudo: required
language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
    - "node_modules"
services:
  - docker
script: "npm run lint"
deploy:
  provider: heroku
  script: bash ./docker_push.sh
  api_key: f437c73f-f814-4fd3-83d7-0ba13ccf9bc6
  on:
    branch: master