sudo: required
language: node_js
node_js:
- 8.9.4
cache:
  directories:
  - node_modules

env: &test_app
- TEST_APP=shri-2018-nodejs-homework-test

aliases:
- &deploy_template
  script: skip
  install: skip
  before_deploy:
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  - docker pull registry.heroku.com/$TEST_APP/web:latest
  - docker tag registry.heroku.com/$TEST_APP/web:latest registry.heroku.com/$APP/web
- &deploy_script
  provider: script
  script:
  - docker push registry.heroku.com/$APP/web

jobs:
  include:
  - stage: unit testing
    script:
    - npm run lint
    - npm run stylelint
    - npm test

  - <<: *deploy_template
    stage: pre integration testing deployment
    env:
    <<: *test_app
    - APP=$TEST_APP
    before_deploy:
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker build --no-cache --tag registry.heroku.com/$APP/web .
    deploy:
      <<: *deploy_script
      on:
        all_branches: true

  - stage: integration testing
    addons:
      sauce_connect:
        username: konstantinov90
        access_key: $SAUCELABS_API_KEY
    script: npm run hermione

  - <<: *deploy_template
    stage: deploy staging
    if: tag IS blank
    env:
    <<: *test_app
    - APP=shri-2018-nodejs-homework-stag
    deploy:
      <<: *deploy_script
      on:
        branch: master

  - <<: *deploy_template
    stage: deploy production
    if: tag IS present
    env:
    <<: *test_app
    - APP=shri-2018-nodejs-homework-prod
    deploy:
      <<: *deploy_script
      on:
        tags: true
