sudo: required
language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
    - "node_modules"
services:
  - docker
script: "npm run lint"
deploy:
  provider: heroku
  script: bash ./docker_push.sh
  api_key:
      secure: PJfNhUgw9p9s3bAfSVif7LL3qUoaZ07j9v33gzAHrq7ZzOKs3XkD0E8dpRr0TQJzjvhLMuj0+8GMvxYZJ6jfmNtCsHuXp+8OZVgDHXnpAaBYsZrp+qrqGA+BOCPhWzUgztBGWqJnKr+5xurvKBlcp+1kBlS7uZTmIMXr0zbtYfO6MJCMeWUlpM3IrY/XZsAMfsB1W8BIwzzYXBZ0iwZ+9HuJ9f63WTBGmwwVntOfJ60FpCcqJr/7kUazp8lfm/Dm8ETtBG3InU/oWsHBxB0vyV8XOGyZFAzGnSoht0NwQy7HU9/iGStsooee2hlIF51Igdp+XqDobaHaZTDOA9JljT0orcWPVBsU8HdpLXWQnSJrVi6RYVJQXSXLHVnC9T/BMDLuK6TLhwXoSvMQNP59STxsEXoQmPpVEXQ14Mgu9cbFtsuu/U6jvziQeXC/bSuq16euQCBUvTZiSG0wikomzCWwjWjdEFubXwm68zz0xbH7+Lg8qDZ/I7PBPIw3LRJSpNfchPYO+kgSbbJQt8orlqQd7uWITqd/gbA1KV47CCUTs+FvM/6aYro4XmFmT5DWCemy/b10WqF4q6g4kccSLbEJDha7+f+ZXoiTOBJher61MSHTVjQrFRAaSvmxNdeSQRhZEPXdrbwLXdwT8E4EKDV4oAmai4DZisv+XF2hreU=
  on:
    branch: master