sudo: required
language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
    - "node_modules"
services:
  - docker
script: "npm run lint"
deploy:
  provider: heroku
  script: bash ./docker_push.sh
  api_key:
      secure: AYWpBTjyKGZw/okAAOoeShxXadyIf2FUq1vpKu5iezeLES/l1NTM78/sLTGtX9sivMU4bwj+QR4vxylay+j8A8jgH8VuuLuvgVi29nI7FmVqjf8MJ9HJQUJlkBa+ee8NXD84jpLo3XvHNhig/zbwUL76Ld3vX5ZWcKOG36ZskCz0Uj3VjIyfBkHEW+8YkxCJehL4lwvruQjXb3gSKu0L8X8Oby12R6QPYpLo3XvHNhig/zbwUL76Ld3vX5ZWcKOG36ZskCz0Uj3VjIyfBkHEW+8YkxCJehL4lwvruQjXb3gSKu0L8X8Oby12R6QPYwJ4A/o2FcaA8yGA3Y2DZ2dzmq6M4vnODLQ1NaQV2Nsl+lSaA4KcQ9UTFfshEN2UaF8cVD9YLVBvuGmxVDmcG4YO6FOV9P4DI22Yby8YFLdSGc1BwhApqcF2ZbSwZN2wMyWQNrHvJGvpU+RmjnNFmIbnE3xb8YWo+C6YmcktLWM5VzPHBSp0jE9Dhpsspff5GVmlyH8BWe12AiGzCfGWBci4wnXGqx4/fEMl+lSaA4KcQ9UTFfshEN2UaF8cVD9YLVBvuGmxVDmcGo1m9OTrZC8xl7kYecQZB+4hWhHyAjmpqAQ7z2QJTJNRKL2LqJ4kin/hU9vDEnM9aaHsnquqS+veIuUjDtiJSuLObM+mo4YO6FOV9P4DI22Yby8YFLdSGc1BwhApqcF2ZbSwZN2wMyWQNrHl7tozcHZi5myjrvNWnK5k8NztZ6Bajd/CIJtre2N2Q2Erus1bSyuXPaKZY1+OXvWZYH76jOE+AOquNmCMha1Bz/rJG2rKKQHZzRVl4G5HdbmqnqOsoTG/GVwUCo64jXW6ogiuZo1m9OTrZC8xl7kYecQZB+4hWhHyAjmpqAQ7z2QJTJNRKL2LqJ4kin/hU9vDEnM9aaHsnquqS+veIuUjDtiJSuLObM+moGl0Ubs=
  on:
    branch: master