sudo: required
language: node_js
node_js:
- 8.9.4
cache:
  directories:
  - node_modules
services:
- docker
jobs:
  include:
  - stage: tests
    script: npm run lint
  - script: npm test
  - &deploy_template
    stage: deploy staging
    if: tag IS blank
    env:
    - APP=shri-2018-nodejs-homework-stag
    script: skip
    before_deploy:
    - docker build --no-cache --tag registry.heroku.com/$APP/web .
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    deploy: &deploy_script
      provider: script
      script:
      - docker push registry.heroku.com/$APP/web
      on:
        branch: master
  - <<: *deploy_template
    stage: deploy production
    if: tag IS present
    env:
    - APP=shri-2018-nodejs-homework-prod
    deploy:
      <<: *deploy_script
      on:
        tags: true
