sudo: required
language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
    - "node_modules"
services:
  - docker
script: "npm run lint"
deploy:
  provider: heroku
  script: bash ./docker_push.sh
  api_key:
      secure: O8Av1fTKA4cHFC9rfteBHz5237XBxkG4gFeVjvWoLbiNPg0zNjXHtySjaUDz4C1Z+jPXEOy+vJJV4+AuwkvvxuEF82k/OgoMADULvWr4YWZ9+EDL6U3OUVaCmCv3bld4PSImqXOpis2CxGYyvW00GXJXIS13R3eQyKhFEI6hvhzo7ValLgIODLgXY/p2nhpCGNwQkbd/LOl1QmLgW9bFcGm1ykmkl8eE1XOpis2CxGYyvW00GXJXIS13R3eQyKhFEI6hvhzo7ValLgIODLgXY/p2nhpCGNwQkbd/LOl1QmLgW9bFcGm1ykmkl8eE1dgZuZh3eKpsOfHhmici1/TplSgjpP1sb2bXhIUyjLjAnVYRLzXD1uasz1cUoSieeITgA1iqHdO4H2GuCzz8/VxVaOxO6MbfCBE6B1nYmx+2w47RZQ80Xxr+Gbn+DBK+YKAgKubVycgyrFNzWaDHf06dx+1jL90XYqm+bDrideWhXdEyVcE6BCCec/oCWSiLEOwMdul+DIyc+F2kfhF2gXjffqEWdIFvtGlAnVYRLzXD1uasz1cUoSieeITgA1iqHdO4H2GuCzz8/LMPCmGZWfIBfo7HKB0Hq2acndCXWeSh+zwCpvFb1xYZHjr+snCG8Mgb68OeFGN/oO9pxxHqGjldghw7Zr+z1T3XoNN7QVxVaOxO6MbfCBE6B1nYmx+2w47RZQ80Xxr+Gbn+DBK+YKAgKubD2qeUKblz9/SNJPC+OR6SF1mP4YP5PwGBypwep8ycCQRqBqom07GJk5k+qPSjqng45UYxJA5YlCKIVHCar0p/oRJJX9h9PmJSVSPSOVyfux7oQ5txcAiCFmp934azBNOLizGBvLMPCmGZWfIBfo7HKB0Hq2acndCXWeSh+zwCpvFb1xYZHjr+snCG8Mgb68OeFGN/oO9pxxHqGjldghw7Zr+z1T3XoNN7QrrJUJA=
  on:
    branch: master