sudo: required
language: node_js
node_js:
- 8.9.4
cache:
  directories:
  - node_modules
services:
- docker
jobs:
  include:
  - stage: tests
    script: npm run lint
  - stage: deploy
    env:
      - APP=shri-2018-nodejs-homework-stag
    script: skip
    before_deploy:
    - docker build --no-cache --tag registry.heroku.com/$APP/web .
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    deploy:
      provider: script
      script:
      - docker push registry.heroku.com/$APP/web
      on:
        branch: master
  # provider: heroku
  # api_key:
  #   secure: vcjB1Ezd3Ste+RaOLBcKb7afFevs49XHSKaFF3V3abQ21iDZctxKqY5weFaI2NJOh+E3ZUYIott8hk9cwOt16AWooSDGO1UMfXSDUnitHwA6tUdHyhR8zeV0znv9AdgYXwgBOpBxHZAbrTzYr6/Ey6dVbIpv4AvCIXc+HFa5/FQLfezm24/DPZ6js0Guh8dbEqqPKhRPEWHLTqnBMupFXLsTLWJibSnI0mYOxpedjhzM3mWbWTXo9SkOewbhe1cN69Bs6h9ro1F8TDCHO0YoWVBD5logieeNV3gLKHfj7HSfA+DFbhIZNw7YOJuiQPr1AjJh/HTFYUmISzRp//CHUsUattZFoG1xLRBN2IfF98j3/1bJlDxICtdb6egLQRH+uoyd8MiAFHhdVyEp3UvB1p8CTcOXudcl7MFUnb8r/ka9Khx5+8mUF7K+2tm9+gLEbP6tgpvmloasdJmOnj0hIJCAmefBH/0JWEy5VPyng8eHukhDSaZmKHDM4Ck5ezPyJGy5K0XZFo8hM6j526vOJbOanar54LBDmRUH1jbXvIZpZ0IDn6QhMIXR50DZ1ich7GrjhCkJpwsKCFpTBvkOl5OpL7pP6NKMQPfd7QQSAE4pFVUUpXt8f7odKKE4F4lMKcDOszaTBqKJNx/K6c85Zuh+VSKAS14ps0sV3JjwBsY=
  # skip_cleanup: true
  # on:
  #   branch: master
  # app: 
  #   master: shri-2018-nodejs-homework-stag
  

  # jobs:
  # include:
  #   - stage: unit tests
  #     script: "Running unit tests (1)"
  #   - stage: unit tests
  #     script: "Running unit tests (2)"
  #   - stage: deploy to staging
  #     script: skip
  #     deploy: &heroku
  #       provider: heroku
  #       app: sf-stages-staging
  #       api_key: $HEROKU_AUTH_TOKEN
  #   - stage: test staging
  #     script: 'curl http://sf-stages-staging.herokuapp.com'
  #   - stage: deploy to production
  #     script: skip
  #     deploy:
  #       <<: *heroku
  #       app: sf-stages-production
  #   - stage: test production
  #     script: 'curl http://sf-stages-production.herokuapp.com'
