sudo: required
language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
    - "node_modules"
services:
  - docker
script: "npm run lint"
deploy:
  provider: heroku
  script: bash ./docker_push.sh
  api_key:
      secure: "v45uJfYX2ixtq5Gc+cepjrN0nzeRlo0hzddjE5ITAonsQoYwubUvj6Qior6pWRtiANK7cLVvw/Onhi9X0Ay2BZp/14XZk0KCECAyl5Lt4szBItAOKhYSOtefMRGxPskt0XbToNcVVH1ZX7PsqzTq/eFq+ePIhQGEQoduefGJ1ZV+4JMwlJpkFTtdpmHfXB/3YdbRVZQFIu67gYMc+pQ+9L6EAbuXH29hKv7MrS8EQ4vqxLnY0m0iJcjBH8OsaW73a9xE5l2oTYcHw/p9AgF0cVBweUIaPyYMXTDGGrvaPgoMZ2gL5IJCoBIwgf23I50FjtmC6DRIaPghWxHkV1IiyOFVb8iRn4DwvPrTIDdn/8GuUbjuPmUisHPyuxMhgxeTVxZ2/DyjBK5EYA4f2yaCEpomsMDXjBRB50c8TCoQZBjeyOtmF1VCvBDi9XiVDkhjarof1x74ize8A4tD2yrjNzj8cQyVp5HSoDd2I4AdHIY0uuLeKHdPjCXeJT/xC+t9wCUPnkuBf53TfwbPN4u5cP1kL8MxRpbjqLIkhCFqm6EDPGEIe4bt6xnq4MdwvkxSbh2sF1Wtw00ka2taXW/kpT0hzqG81k95MJ1JqQqEURHCsN7g/P36kMdPb8b0OsZiJj9ReRh7kKaZ/dp/QQ3jr/a+c5DLCoIAUwT2mCqGoI0="
  on:
    branch: master